# python learning

## Tutorial 1 to 4

datatypes


In [91]:
1+1

2

In [92]:
4*5

20

In [93]:
10**2

100

In [94]:
'string'

'string'

In [95]:
10*'ankit'

'ankitankitankitankitankitankitankitankitankitankit'

In [96]:
type('ankit')

str

In [97]:
type(0.1)

float

In [98]:
a=11
b=3

print(a*2)
print(a+b)
print(a%b)

22
14
2


In [99]:
first_name = "ankit"
last_name = " raut"
print("my first name is {a} and my last name is{b}".format(b=last_name,a=first_name))

my first name is ankit and my last name is raut


In [100]:
len('ankit')

5

In [101]:
str='ankit'
print(str.isalnum())
print(str.isalpha())
print(str.startswith('A'))
print(str.endswith('t'))
print(str.capitalize())
print(str.lower())


True
True
False
True
Ankit
ankit


In [102]:
True or False

True

In [103]:
True and False

False

In [104]:
True and True

True

In [105]:
a=False and False
b=True or False
print("C =a or b = {c}".format(c= a or b))

C =a or b = True


In [106]:
print('1 or 1 = {a}'.format(a= 1 or 1))

1 or 1 = 1


In [107]:
False and False

False

# list

In [108]:
type([])

list

In [109]:
india=list()
type(india)

list

In [110]:
india=["maharashtra","Gujrat",'U.P','M.P','Punjab',"Rajstan"]

In [111]:
## indexing
india[0:5]

['maharashtra', 'Gujrat', 'U.P', 'M.P', 'Punjab']

In [112]:
## indexing
india[2]

'U.P'

In [113]:
print("area wise largest state is {a}".format(a=india[5]))

area wise largest state is Rajstan


In [114]:
india.append("bihar")

In [115]:
india.append("C.G")

In [116]:
india

['maharashtra', 'Gujrat', 'U.P', 'M.P', 'Punjab', 'Rajstan', 'bihar', 'C.G']

In [117]:
len(india)

8

In [118]:
##insert
india.insert(3,"Delhi")

In [119]:
india

['maharashtra',
 'Gujrat',
 'U.P',
 'Delhi',
 'M.P',
 'Punjab',
 'Rajstan',
 'bihar',
 'C.G']

In [120]:
##india.append(["H.p","A.P"])

In [121]:
india

['maharashtra',
 'Gujrat',
 'U.P',
 'Delhi',
 'M.P',
 'Punjab',
 'Rajstan',
 'bihar',
 'C.G']

In [122]:
india.insert(1,["H.P","A.P"])

In [123]:
india

['maharashtra',
 ['H.P', 'A.P'],
 'Gujrat',
 'U.P',
 'Delhi',
 'M.P',
 'Punjab',
 'Rajstan',
 'bihar',
 'C.G']

In [124]:
india.extend(['J&K',"TN"])

In [125]:
india

['maharashtra',
 ['H.P', 'A.P'],
 'Gujrat',
 'U.P',
 'Delhi',
 'M.P',
 'Punjab',
 'Rajstan',
 'bihar',
 'C.G',
 'J&K',
 'TN']

In [126]:
lst=list()
type(lst)

list

In [127]:
lst=[1,2,2,2,2,3,4,6]
lst.count(2)

4

In [128]:
lst.insert(4,11)

In [129]:
lst

[1, 2, 2, 2, 11, 2, 3, 4, 6]

In [130]:
sum(lst)

33

In [131]:
lst.reverse()

In [132]:
lst

[6, 4, 3, 2, 11, 2, 2, 2, 1]

In [133]:
2*(lst)

[6, 4, 3, 2, 11, 2, 2, 2, 1, 6, 4, 3, 2, 11, 2, 2, 2, 1]

In [134]:
lst.pop(0)

6

In [135]:
lst

[4, 3, 2, 11, 2, 2, 2, 1]

In [136]:
lst.pop()

1

In [137]:
lst

[4, 3, 2, 11, 2, 2, 2]

In [138]:
lst.pop(1)

3

In [139]:
lst

[4, 2, 11, 2, 2, 2]

In [140]:
lst.count(2)

4

In [141]:
len(lst)

6

In [142]:
lst.index(2,0,6)

1

In [143]:
alpha=list()

In [144]:
alpha=["a","a","g","k","a"]

In [145]:
alpha.count("a")

3

In [146]:
alpha.index("a",2,5)

4

In [147]:
## minimum number of list (smallest number in list)
min(lst)

2

In [148]:
## maximum number in list
max(lst)

11

## SET

In [149]:
set_var=set()
type(set_var)
print(type(set_var))

<class 'set'>


In [150]:
set_var={'Avengers','Hitman','spiderman','Batman'}

In [151]:
set_var.add('Hulk')

In [152]:
set_var

{'Avengers', 'Batman', 'Hitman', 'Hulk', 'spiderman'}

In [153]:
set1={'Avengers', 'Batman', 'Hitman', 'Hulk', 'spiderman'}
set2={'Avengers', 'Batman', 'Hitman', 'Hulk', 'spiderman','Thanos'}

In [154]:
set2.intersection(set1)

{'Avengers', 'Batman', 'Hitman', 'Hulk', 'spiderman'}

In [155]:
print(set2)

{'Hitman', 'Hulk', 'spiderman', 'Batman', 'Avengers', 'Thanos'}


In [156]:
set2.intersection_update(set1)

In [157]:
print(set2)

{'Hitman', 'Hulk', 'spiderman', 'Batman', 'Avengers'}


In [158]:
set2.difference(set1)

set()

In [159]:
print(set2)

{'Hitman', 'Hulk', 'spiderman', 'Batman', 'Avengers'}


In [160]:
set2.difference_update(set1)

In [161]:
set2

set()

## Dictionary

In [162]:
dic={}

In [163]:
type(dic)

dict

In [164]:
my_dict={"car1":"audi" , "car2":"BMW", "car3":"mercidies"}

In [165]:
type(my_dict)

dict

In [166]:
my_dict["car1"]

'audi'

In [167]:
## for loop

for x in my_dict:
    print(x)

car1
car2
car3


In [168]:
for x in my_dict.values():
    print(x)

audi
BMW
mercidies


In [169]:
for x in my_dict.items():
    print(x)

('car1', 'audi')
('car2', 'BMW')
('car3', 'mercidies')


In [170]:
my_dict['car4']='audi2.0'

In [171]:
my_dict

{'car1': 'audi', 'car2': 'BMW', 'car3': 'mercidies', 'car4': 'audi2.0'}

In [172]:
my_dict['car1']='maruti'
my_dict

{'car1': 'maruti', 'car2': 'BMW', 'car3': 'mercidies', 'car4': 'audi2.0'}

## nested dictionaries

In [173]:
car1_model={'mercedies':1980}
car2_model={'audi':1990}
car3_model={'BMW':1985}

car_type={'car1':car1_model , 'car2':car2_model , 'car3':car3_model}

print(car_type)

{'car1': {'mercedies': 1980}, 'car2': {'audi': 1990}, 'car3': {'BMW': 1985}}


In [174]:
print(car_type['car1'])

{'mercedies': 1980}


In [175]:
print(car_type['car1']['mercedies'])

1980


In [176]:
print(car_type['car3'])

{'BMW': 1985}


In [177]:
print(car_type['car3']['BMW'])

1985


## tuples

In [178]:
my_tuples=()
type(my_tuples)

tuple

In [179]:
my_tuples=('paris','mumbai','new york','london')

In [180]:
my_tuples=my_tuples*200

In [181]:
my_tuples

('paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',
 'mumbai',
 'new york',
 'london',
 'paris',


In [182]:
my_tuples.count('paris')

200

In [183]:
my_tuples.index('paris')

0

## numpy

In [184]:
import numpy as np

In [185]:
roll_number=[1,2,3,4,5]

In [186]:
arr=np.array(roll_number)

In [187]:
type(arr)

numpy.ndarray

In [188]:
print(arr)

[1 2 3 4 5]


In [189]:
arr.shape

(5,)

In [203]:
ro_num_a=[1,2,4,5,7,8]
ro_num_b=[3,1,5,2,2,4]
ro_num_c=[9,0,6,4,3,2]

In [204]:
arr=np.array([ro_num_a,ro_num_b,ro_num_c])

In [205]:
arr

array([[1, 2, 4, 5, 7, 8],
       [3, 1, 5, 2, 2, 4],
       [9, 0, 6, 4, 3, 2]])

In [193]:
arr.shape

(3, 6)

In [194]:
arr.reshape(2,9)

array([[1, 2, 4, 5, 7, 8, 3, 1, 5],
       [2, 2, 4, 9, 0, 6, 4, 3, 2]])

In [195]:
arr=([1, 2, 4, 5, 7, 8, 3, 1, 5])

In [196]:
arr[4]

7

In [206]:
arr

array([[1, 2, 4, 5, 7, 8],
       [3, 1, 5, 2, 2, 4],
       [9, 0, 6, 4, 3, 2]])

In [208]:
arr[1:,2:4]

array([[5, 2],
       [6, 4]])

In [209]:
arr[2:,1:2]

array([[0]])

In [222]:
arr=np.arange(0,10,step=2)

In [223]:
arr

array([0, 2, 4, 6, 8])

In [224]:
np.linspace(1,4,num=5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [225]:
arr

array([0, 2, 4, 6, 8])

In [226]:
## After copy it will locate diffrent memory location to different array.
arr1=arr.copy()

In [227]:
print(arr1)

[0 2 4 6 8]


In [231]:
arr1[2:4]=100

In [232]:
print(arr1)

[  0   2 100 100   8]


In [233]:
print(arr)

[0 2 4 6 8]


In [234]:
arr2=arr.copy()

In [235]:
print(arr2)

[0 2 4 6 8]


In [238]:
arr2[3:]=100

In [239]:
print(arr2)

[  0   2   4 100 100]


In [240]:
print(arr)

[0 2 4 6 8]


In [50]:
import numpy as np

In [51]:
vitry=[1,2,4,5,7,8]
creteil=[3,1,5,2,2,4]
val_de_marne=[9,0,6,4,3,2]
VDM=np.array([vitry,creteil,val_de_marne])

In [52]:
print(VDM)

[[1 2 4 5 7 8]
 [3 1 5 2 2 4]
 [9 0 6 4 3 2]]


In [53]:
VDM[VDM<4]

array([1, 2, 3, 1, 2, 2, 0, 3, 2])

In [54]:
VDM.shape

(3, 6)

In [55]:
VDM.reshape(9,2)

array([[1, 2],
       [4, 5],
       [7, 8],
       [3, 1],
       [5, 2],
       [2, 4],
       [9, 0],
       [6, 4],
       [3, 2]])

In [56]:
type(VDM)

numpy.ndarray

In [57]:
VDM*2

array([[ 2,  4,  8, 10, 14, 16],
       [ 6,  2, 10,  4,  4,  8],
       [18,  0, 12,  8,  6,  4]])

In [58]:
VDM>3

array([[False, False,  True,  True,  True,  True],
       [False, False,  True, False, False,  True],
       [ True, False,  True,  True, False, False]])

In [59]:
VDM/2

array([[0.5, 1. , 2. , 2.5, 3.5, 4. ],
       [1.5, 0.5, 2.5, 1. , 1. , 2. ],
       [4.5, 0. , 3. , 2. , 1.5, 1. ]])

In [60]:
VDM%2

array([[1, 0, 0, 1, 1, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0]], dtype=int32)

In [61]:
np.ones((4,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [62]:
np.ones((4,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [71]:
vdm_ex=np.random.rand()

In [72]:
vdm_ex

0.08969820793134153

In [65]:
type(vdm_ex)

numpy.ndarray

In [74]:
np.random.randn(4,4)
## dont know standard normal distributution see a video

array([[-0.84047197,  0.76985809,  0.83420352,  0.06036941],
       [-0.59662551,  0.14697918, -0.29063145, -0.82392822],
       [ 0.52204553, -0.10224773,  0.70185491,  1.21873289],
       [-0.63008502,  1.01184202, -0.32534902,  1.88660214]])

In [78]:
np.random.randint(20,200,15).reshape(3,5)

array([[175,  76, 156,  29,  42],
       [122, 149, 117,  48,  99],
       [ 28, 109, 164, 190,  50]])

In [80]:
np.random.random_sample((2,5))

array([[0.70272627, 0.31710753, 0.53623945, 0.96256371, 0.98791537],
       [0.62104624, 0.97464893, 0.79305762, 0.09850962, 0.12023447]])